FROM caddy:builder AS builder
# currently broken, see: https://github.com/caddy-dns/route53/issues/58
# RUN xcaddy build \
#     --with github.com/caddy-dns/route53
# fix: pin lst working versions
RUN xcaddy build v2.9.1 --with github.com/caddy-dns/route53@v1.5.0 
FROM caddy:latest
COPY --from=builder /usr/bin/caddy /usr/bin/caddy