FROM caddy:builder AS builder
RUN xcaddy build \
    --with github.com/greenpau/caddy-security \
    --with github.com/caddy-dns/cloudflare \
    --with github.com/WeidiDeng/caddy-cloudflare-ip \
    --with github.com/lanrat/caddy-dynamic-remoteip
FROM caddy:latest
COPY --from=builder /usr/bin/caddy /usr/bin/caddy