name: Docker Build and Publish

# TODO: automate when base image updates: https://github.com/mthalman/docker-bump-action
on:
  schedule:
    - cron: '37 7 * * *'
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**/README.md'
      - 'LICENSE'
      - '.vscode/**'
  workflow_dispatch:

env:
  ## github.repository as <account>/<repo>
  #IMAGE_NAME: ${{ github.repository }}
  IMAGE_NAME_PREFIX: ${{ github.actor }}/caddy

# TODO: possible method for making dynamic based oon dockerfiles
# https://gist.github.com/maniankara/db341998b13b22e182e18d3a22bd7c8a
# current method based on: https://github.com/docker/build-push-action/issues/561#issuecomment-1054596444
jobs:
  ## define job to build and publish docker image
  build-and-push-image:
    name: Build Docker image and push to Github Container Registry
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        include:
          - dockerfile: Dockerfile.cloudflare
            variant: cloudflare
          - dockerfile: Dockerfile.route53
            variant: route53

    steps:
      ## https://github.com/actions/checkout
      - name: Checkout repository
        uses: actions/checkout@v4

      ## https://github.com/docker/build-push-action
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      ## https://github.com/docker/login-action
      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # ## https://github.com/docker/metadata-action
      # - name: Extract Docker metadata
      #   id: meta
      #   uses: docker/metadata-action@v5
      #   with:
      #     images: docker.io/caddy
      #     tags: |
      #       type=semver,pattern={{version}}
      #       type=semver,pattern={{major}}.{{minor}}
      #       type=semver,pattern={{major}}
      #     flavor: |
      #       latest=true
  
      ## https://github.com/docker/build-push-action
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v6
        with:
          provenance: false
          context: .
          #platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          # tags: ${{ steps.meta.outputs.tags }}
          # labels: ${{ steps.meta.outputs.labels }}
          tags: |
            ghcr.io/${{ env.IMAGE_NAME_PREFIX }}-${{ matrix.variant }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file:  ${{ matrix.dockerfile }}

      - name: Image digest
        run: echo ${{ steps.build-and-push.outputs.digest }}
